name: CI/CD

on:

  push:

    branches: [ "main" ]

# https://www.programonaut.com/how-to-host-an-application-on-a-server-vps-using-docker/
jobs:

  publish:

    name: CI
    
    runs-on: ubuntu-latest

    permissions:

      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      
      # https://github.com/docker/login-action?tab=readme-ov-file
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build et push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alexismelo/portfolio:latest

  deploy:

    needs: publish

    name: CD

    runs-on: ubuntu-latest

    steps:

      # check this thread to understand why its needed:
      # <https://stackoverflow.com/a/70447517>
      # -> je comprend rien mais on fait confiance :)
      - name: Installation des clés SSH
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.VPS_SSH_HOST }} > ~/.ssh/known_hosts

      - name: Déploiement sur VPS
        run: ssh ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }} "cd ${{ vars.VPS_WORK_DIR }} && docker compose pull && docker compose up -d && exit"

      - name: Nettoyage clés SSH
        run: rm -rf ~/.ssh

